ARG NODE_IMAGE=node:20-bullseye
FROM ${NODE_IMAGE}

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . /app

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
